export const ACTION = {
    GET_LOADING     : "GET_LOADING ",

    GET_ALL_OVERVIEW    : "GET_ALL_OVERVIEW ",
    GET_ALL_OVERVIEW_SUCCESS   : "GET_ALL_OVERVIEW_SUCCESS ",

    GET_ALL_ROOM    : "GET_ALL_ROOM ",
    GET_ALL_ROOM_SUCCESS   : "GET_ALL_ROOM_SUCCESS ",
    
    GET_ALL_SERVICE    : "GET_ALL_SERVICE ",
    GET_ALL_SERVICE_SUCCESS   : "GET_ALL_SERVICE_SUCCESS ",

 
    GET_ALL_ORDER  : "GET_ALL_ORDER",
    GET_ALL_ORDER_SUCCESS : "GET_ALL_ORDER_SUCCESS",
    
}